// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.7.0.0
//      SpecFlow Generator Version:3.7.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MAR.API.MortgageCalculator.QA.Tests.Features.CalculateController
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.7.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PaidFeature : object, Xunit.IClassFixture<PaidFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Paid.feature"
#line hidden
        
        public PaidFeature(PaidFeature.FixtureData fixtureData, MAR_API_MortgageCalculator_QA_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/CalculateController", "Paid", "\t/Calculate endpoint", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate (paid) endpoint returns successful response for request with HOA")]
        [Xunit.TraitAttribute("FeatureTitle", "Paid")]
        [Xunit.TraitAttribute("Description", "Calculate (paid) endpoint returns successful response for request with HOA")]
        [Xunit.TraitAttribute("Category", "CalculateControllerTests")]
        public virtual void CalculatePaidEndpointReturnsSuccessfulResponseForRequestWithHOA()
        {
            string[] tagsOfScenario = new string[] {
                    "CalculateControllerTests"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate (paid) endpoint returns successful response for request with HOA", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 5
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
 testRunner.Given("I want to call the API CalculateController \'\' resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table5.AddRow(new string[] {
                            "PurchasePrice",
                            "100000.00"});
                table5.AddRow(new string[] {
                            "APR",
                            "2.75"});
                table5.AddRow(new string[] {
                            "LoanTermYears",
                            "30"});
                table5.AddRow(new string[] {
                            "DownPaymentPercent",
                            "20"});
                table5.AddRow(new string[] {
                            "PropertyTaxRate",
                            "1.15"});
                table5.AddRow(new string[] {
                            "HomeownerInsuranceRate",
                            "0.22"});
                table5.AddRow(new string[] {
                            "HOAMonthly",
                            "10"});
#line 7
 testRunner.And("with this API MortgageCalculationRequest", ((string)(null)), table5, "And ");
#line hidden
#line 16
 testRunner.When("I call the API using POST, the url and the request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 17
 testRunner.Then("the API HTTP response is successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 18
 testRunner.And("the API HTTP domain response data is correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table6.AddRow(new string[] {
                            "MortgagePaymentyMonthly",
                            "326.59"});
                table6.AddRow(new string[] {
                            "PropertyTaxPaymentMonthly",
                            "95.83"});
                table6.AddRow(new string[] {
                            "HomeownersInsurancePaymentMonthly",
                            "18.33"});
                table6.AddRow(new string[] {
                            "DownPayment",
                            "20000"});
                table6.AddRow(new string[] {
                            "TermInterestPaid",
                            "37573.46"});
#line 19
 testRunner.And("the API HTTP response Data matches this successful MortgageCalculationResult", ((string)(null)), table6, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate (paid) endpoint returns successful response for request without HOA")]
        [Xunit.TraitAttribute("FeatureTitle", "Paid")]
        [Xunit.TraitAttribute("Description", "Calculate (paid) endpoint returns successful response for request without HOA")]
        [Xunit.TraitAttribute("Category", "CalculateControllerTests")]
        public virtual void CalculatePaidEndpointReturnsSuccessfulResponseForRequestWithoutHOA()
        {
            string[] tagsOfScenario = new string[] {
                    "CalculateControllerTests"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate (paid) endpoint returns successful response for request without HOA", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 28
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 29
 testRunner.Given("I want to call the API CalculateController \'\' resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table7.AddRow(new string[] {
                            "PurchasePrice",
                            "100000.00"});
                table7.AddRow(new string[] {
                            "APR",
                            "2.75"});
                table7.AddRow(new string[] {
                            "LoanTermYears",
                            "30"});
                table7.AddRow(new string[] {
                            "DownPaymentPercent",
                            "20"});
                table7.AddRow(new string[] {
                            "PropertyTaxRate",
                            "1.15"});
                table7.AddRow(new string[] {
                            "HomeownerInsuranceRate",
                            "0.22"});
                table7.AddRow(new string[] {
                            "HOAMonthly",
                            "0"});
#line 30
 testRunner.And("with this API MortgageCalculationRequest", ((string)(null)), table7, "And ");
#line hidden
#line 39
 testRunner.When("I call the API using POST, the url and the request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 40
 testRunner.Then("the API HTTP response is successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
 testRunner.And("the API HTTP domain response data is correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Field",
                            "Value"});
                table8.AddRow(new string[] {
                            "MortgagePaymentyMonthly",
                            "326.59"});
                table8.AddRow(new string[] {
                            "PropertyTaxPaymentMonthly",
                            "95.83"});
                table8.AddRow(new string[] {
                            "HomeownersInsurancePaymentMonthly",
                            "18.33"});
                table8.AddRow(new string[] {
                            "DownPayment",
                            "20000"});
                table8.AddRow(new string[] {
                            "TermInterestPaid",
                            "37573.46"});
#line 42
 testRunner.And("the API HTTP response Data matches this successful MortgageCalculationResult", ((string)(null)), table8, "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.7.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                PaidFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                PaidFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
