// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.7.0.0
//      SpecFlow Generator Version:3.7.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace MAR.API.MortgageCalculator.QA.Tests.Features.CalculateController.Bulk
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.7.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BulkFeature : object, Xunit.IClassFixture<BulkFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Bulk.feature"
#line hidden
        
        public BulkFeature(BulkFeature.FixtureData fixtureData, MAR_API_MortgageCalculator_QA_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features/CalculateController/Bulk", "Bulk", "\tAs a consumer\r\n\tI want to be able to request multiple mortgage calculations in o" +
                    "ne request\r\n\tSo that I can see multiple responses at once", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Calculate (bulk) endpoint returns successful response for request with length 3")]
        [Xunit.TraitAttribute("FeatureTitle", "Bulk")]
        [Xunit.TraitAttribute("Description", "Calculate (bulk) endpoint returns successful response for request with length 3")]
        [Xunit.TraitAttribute("Category", "CalculateControllerTests")]
        [Xunit.TraitAttribute("Category", "DeploymentSmokeTests")]
        public virtual void CalculateBulkEndpointReturnsSuccessfulResponseForRequestWithLength3()
        {
            string[] tagsOfScenario = new string[] {
                    "CalculateControllerTests",
                    "DeploymentSmokeTests"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calculate (bulk) endpoint returns successful response for request with length 3", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given("I issue an authorization token successfully to ScenarioContext", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.And("I want to call the API CalculateController \'bulk\' resource", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 10
 testRunner.And("with the correct API authorization headers setup for an endpoint requiring author" +
                        "ization from ScenarioContext", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "PurchasePrice",
                            "APR",
                            "LoanTermYears",
                            "DownPaymentPercent",
                            "PropertyTaxRate",
                            "HomeownerInsuranceRate",
                            "HOAMonthly"});
                table1.AddRow(new string[] {
                            "100000.00",
                            "2.75",
                            "30",
                            "20",
                            "1.15",
                            "0.22",
                            "10"});
                table1.AddRow(new string[] {
                            "120000.00",
                            "2.75",
                            "30",
                            "20",
                            "1.15",
                            "0.22",
                            "0"});
                table1.AddRow(new string[] {
                            "100000.00",
                            "2.75",
                            "30",
                            "20",
                            "1.15",
                            "0.22",
                            "0"});
#line 11
 testRunner.And("I have these API MortgageCalculationRequests for a bulk request", ((string)(null)), table1, "And ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "MortgagePaymentyMonthly",
                            "PropertyTaxPaymentMonthly",
                            "HomeownersInsurancePaymentMonthly",
                            "DownPayment",
                            "TermInterestPaid"});
                table2.AddRow(new string[] {
                            "326.59",
                            "95.83",
                            "18.33",
                            "20000",
                            "37573.46"});
                table2.AddRow(new string[] {
                            "391.91",
                            "115.00",
                            "22.00",
                            "24000",
                            "45088.15"});
                table2.AddRow(new string[] {
                            "326.59",
                            "95.83",
                            "18.33",
                            "20000",
                            "37573.46"});
#line 16
 testRunner.And("I have these API MortgageCalculationResults for a bulk request", ((string)(null)), table2, "And ");
#line hidden
#line 21
 testRunner.And("I merged the API mortgage calculation Requests and Responses into the expected Mo" +
                        "rtgageCalculationResults collection", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 22
 testRunner.And("I have created the API BulkMortgageCalculationRequest from ScenarioContext data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 23
 testRunner.When("I call the API using POST, the url, the headers and the request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 24
 testRunner.Then("the API HTTP response is successful", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 25
 testRunner.And("the API HTTP domain response data is correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 26
 testRunner.And("the API HTTP response Data matches the expected MortgageCalculationResults collec" +
                        "tion", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.7.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                BulkFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                BulkFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
